# Generated by Django 4.2 on 2023-09-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodAdvice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_id", models.CharField(max_length=10)),
                ("category_name", models.CharField(max_length=100, null=True)),
                ("name", models.CharField(max_length=100)),
                ("name_subtitle", models.CharField(max_length=100, null=True)),
                ("keywords", models.CharField(max_length=300, null=True)),
                ("pantry_max_days", models.CharField(max_length=100)),
                ("pantry_tips", models.CharField(max_length=300)),
                (
                    "fridge_needed",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5, null=True
                    ),
                ),
                ("refrigerate_max_days", models.PositiveIntegerField(null=True)),
                ("refrigerate_ao_max_days", models.PositiveIntegerField(null=True)),
                ("refrigerate_tips", models.CharField(max_length=300)),
                (
                    "freeze_recommended",
                    models.CharField(
                        choices=[("Yes", "Yes"), ("No", "No")], max_length=5, null=True
                    ),
                ),
                ("compost", models.CharField(max_length=10)),
                ("food_waste_index", models.CharField(max_length=100)),
            ],
        ),
    ]
