# Generated by Django 4.2 on 2023-09-23 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_foodhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_id', models.CharField(max_length=10)),
                ('action_type', models.CharField(choices=[('ThrownAway', 'ThrownAway'), ('ThrownAway', 'Upcycled')], max_length=10)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='foodhistory',
            name='food_id',
        ),
        migrations.AddField(
            model_name='foodhistory',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.foodadvice'),
        ),
    ]
