# Generated by Django 4.2 on 2023-09-23 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracker", "0003_foodaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foodaction",
            name="name",
        ),
        migrations.AlterField(
            model_name="foodaction",
            name="food_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tracker.foodadvice",
            ),
        ),
    ]
