# Generated by Django 4.2 on 2023-09-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_foodhistory_eaten'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhistory',
            name='name',
        ),
    ]
