# Generated by Django 4.2 on 2023-09-24 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_foodhistory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodhistory',
            name='name',
        ),
    ]
