# Generated by Django 4.2 on 2023-09-25 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_foodaction_name_alter_foodaction_food_id'),
        ('tracker', '0008_alter_foodhistory_eaten'),
    ]

    operations = [
    ]
