# Generated by Django 4.2 on 2023-09-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_merge_20230925_0033'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodAction',
        ),
    ]
